name: Actions master

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package spring-boot:repackage -DskipTests

    runs-on: ubuntu-latest

  code_analysis:
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    # - name: Analize
    #   run: mvn org.sonarsource.scanner.maven:sonar

    - name: SonarCloud Scan
      # uses: sonarsource/sonarcloud-github-action@master
      run: mvn sonar:sonar -Dsonar.projectVersion=${{ github.run_number }} -Dsonar.organization=miavega -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      # with:
      #   args: >
      #     -Dsonar.projectVersion=${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    runs-on: ubuntu-latest
